-- TO CREATE DATABASE
CREATE DATABASE INSTITUTE;

-- TO USE DATABASE
USE INSTITUTE;

-- TO CREATE TABLE
CREATE TABLE FACULTY (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NAME VARCHAR(250),
EMAIL VARCHAR(250),
SALARY INT 
);

-- TO DISPLAY THE TABLE
SELECT * FROM FACULTY;

-- TO INSERT VALUES INTO TABLE
INSERT INTO FACULTY VALUES (null, "Arsalan", "a@gmail.com", 50000);  
INSERT INTO FACULTY VALUES (null, "Hasan", "b@gmail.com", 45000);  
INSERT INTO FACULTY VALUES (null, "Zaid", "c@gmail.com", 35000);  
INSERT INTO FACULTY VALUES (null, "Ali", "d@gmail.com", 30000);  
INSERT INTO FACULTY VALUES (null, "Saad", "e@gmail.com", 20000);  

-- TO CREATE TABLE WITH FOREIGN KEY
CREATE TABLE STUDENTS (
ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
STUDENT_NAME VARCHAR(250),
COURSE VARCHAR(250),
FACULTY_NAME INT,
FOREIGN KEY (FACULTY_NAME)
REFERENCES FACULTY (ID)
); 

-- TO DISPLAY THE TABLE
SELECT * FROM STUDENTS;

-- TO INSERT VALUES INTO TABLE
INSERT INTO STUDENTS VALUES (null, "Khuzaima", "SQL", 1);   
INSERT INTO STUDENTS VALUES (null, "Yousuf", "SQL", 1);   
INSERT INTO STUDENTS VALUES (null, "Shoaib", "SQL", 1);   
INSERT INTO STUDENTS VALUES (null, "Muneeb", "SQL", 1);   
INSERT INTO STUDENTS VALUES (null, "Zubair", "PHP", 3);   
INSERT INTO STUDENTS VALUES (null, "Abdullah", "PYTHON", 5);   
INSERT INTO STUDENTS VALUES (null, "Umar", "OFFICE", 3);   
INSERT INTO STUDENTS VALUES (null, "Hammad", "PYTHON", 5);   
INSERT INTO STUDENTS VALUES (null, "Usman", "APPDEVELOPMENT", 5);   
INSERT INTO STUDENTS VALUES (null, "Irfan", "DATA SCIENCE", null);   

-- TO JOIN TABLES USING INNER JOIN
SELECT 
    STUDENT_NAME, COURSE, FACULTY_NAME
FROM
    FACULTY
        INNER JOIN
    STUDENTS ON STUDENTS.FACULTY_NAME = FACULTY.ID;
    
-- TO JOIN TABLES USING LEFT JOIN
SELECT 
    STUDENT_NAME, COURSE, FACULTY_NAME
FROM
    FACULTY
        LEFT JOIN
    STUDENTS ON STUDENTS.FACULTY_NAME = FACULTY.ID;

-- TO JOIN TABLES USING RIGHT JOIN
SELECT 
    STUDENT_NAME, COURSE, FACULTY_NAME
FROM
    FACULTY
        RIGHT JOIN
    STUDENTS ON STUDENTS.FACULTY_NAME = FACULTY.ID;
    
-- TO RETRIEVE DATA FROM TWO TABLES USING UNION
SELECT 
    STUDENT_NAME, COURSE, FACULTY_NAME
FROM
    FACULTY
        RIGHT JOIN
    STUDENTS ON STUDENTS.FACULTY_NAME = FACULTY.ID
UNION 
SELECT 
    STUDENT_NAME, COURSE, FACULTY_NAME
FROM
    FACULTY
        LEFT JOIN
    STUDENTS ON STUDENTS.FACULTY_NAME = FACULTY.ID;




