-- TO CREATE DATABASE
CREATE DATABASE ABC;

-- TO USE DATABASE
USE ABC;

-- TO CREATE TABLE
CREATE TABLE STUDENT (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(250),
    COURSE VARCHAR(250)
);

-- TO DISPLAY THE TABLE
SELECT 
    *
FROM
    STUDENT; 

-- TO INSERT VALUES INTO TABLE
INSERT INTO STUDENT VALUES (NULL, "Khuzaima", "SQL");
INSERT INTO STUDENT VALUES (NULL, "Ahsan", "Office");
INSERT INTO STUDENT VALUES (NULL, "Hassan", "HTML");
INSERT INTO STUDENT VALUES (NULL, "Yousuf", "SQL");
INSERT INTO STUDENT VALUES (NULL, "Ayesha", "Bootstrap");
INSERT INTO STUDENT VALUES (NULL, "Hafsa", "JavaScript");
INSERT INTO STUDENT VALUES (NULL, "Zubair", "PYTHON");
INSERT INTO STUDENT VALUES (NULL, "Shoaib", "SQL");
INSERT INTO STUDENT VALUES (NULL, "Muneeb", "SQL");
INSERT INTO STUDENT VALUES (NULL, "Uzma", "PHP");

-- TO CREATE A STORED PROCEDURE TO DISPLAY THE TABLE
DELIMITER // 
CREATE PROCEDURE SelectData()
BEGIN
  -- SELECT ALL DATA FROM THE STUDENT TABLE
  SELECT * FROM STUDENT;
END
// DELIMITER;

-- CALL THE STORED PROCEDURE TO DISPLAY THE TABLE
CALL SelectData();

-- TO CREATE A STORED PROCEDURE TO INSERT VALUES
DELIMITER //
CREATE PROCEDURE INSERTDATA(STDNAME VARCHAR(250), CRSE VARCHAR(250))
BEGIN
  -- INSERT VALUES INTO THE STUDENT TABLE
  INSERT INTO STUDENT (NAME, COURSE) VALUES (STDNAME, CRSE);
END 
//

-- CALL THE STORED PROCEDURE TO INSERT VALUES
CALL INSERTDATA("Abrar", "SQL");
CALL INSERTDATA("Bushra", "PHP");
CALL INSERTDATA("Sara", "PYTHON");
CALL INSERTDATA("Shahid", "PYTHON");

-- TO CREATE A STORED PROCEDURE TO DELETE VALUES
DELIMITER //
CREATE PROCEDURE DELETEDATA(STDNAME VARCHAR(250))
BEGIN 
  -- DELETE VALUES FROM THE STUDENT TABLE
  DELETE FROM STUDENT WHERE NAME = STDNAME;
END 
//

-- CALL THE STORED PROCEDURE TO DELETE VALUES
CALL DELETEDATA("Shahid");
CALL DELETEDATA("Uzma");
CALL DELETEDATA("Hassan");
CALL DELETEDATA("Hafsa");

-- TO CREATE A STORED PROCEDURE TO SEARCH DATA BY NAME
DELIMITER //
CREATE PROCEDURE SEARCHBYNAME(STDNAME VARCHAR(250))
BEGIN
  -- SELECT DATA FROM THE STUDENT TABLE BASED ON THE NAME
  SELECT * FROM STUDENT WHERE NAME = STDNAME;
END
//

-- CALL THE STORED PROCEDURE TO SEARCH DATA BY NAME
CALL SEARCHBYNAME("Yousuf");
CALL SEARCHBYNAME("Khuzaima");
CALL SEARCHBYNAME("Shoaib");
CALL SEARCHBYNAME("Muneeb");

-- TO CREATE A STORED PROCEDURE TO UPDATE STUDENT DATA
DELIMITER //

CREATE PROCEDURE UPDATEDATA(STDNAME VARCHAR(250), CRSE VARCHAR(250), STDNTNAME VARCHAR(250))
BEGIN
  -- USE THE UPDATE STATEMENT TO MODIFY DATA IN THE STUDENT TABLE
  UPDATE STUDENT SET NAME = STDNAME, COURSE = CRSE WHERE NAME = STDNTNAME;
END
//

-- TO CALL THE STORED PROCEDURE TO UPDATE STUDENT DATA
CALL UPDATEDATA("Irfan", "PHP", "Zubair");
CALL UPDATEDATA("Asad", "APPDEVELOPMENT", "Abrar");
CALL UPDATEDATA("Umar", "CPISM", "Ayesha");
