-- TO CREATE DATABASE
CREATE DATABASE APTECH;

-- TO USE DATABASE 
USE APTECH;

-- TO CREATE TABLE 
CREATE TABLE INFO(
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(250),
CONTACT VARCHAR(250),
AGE INT
);

-- TO SELECT FROM TABLE 
SELECT * FROM INFO;
