-- TO CREATE DATABASE
CREATE DATABASE SHAHEEN_E_IQBAL;

-- TO USE DATABASE
USE SHAHEEN_E_IQBAL;

-- TO CREATE TABLE
CREATE TABLE STUDENTS (
ID INT,
NAME VARCHAR(250),
AGE INT 
);

-- TO SELECT TABLE
SELECT * FROM STUDENTS;

-- TO INSERT VALUES
INSERT INTO STUDENTS values(NULL,"Khuzaima",23);
INSERT INTO STUDENTS values(NULL,"Yousuf",20);
INSERT INTO STUDENTS values(NULL,"Shoaib",21);
INSERT INTO STUDENTS values(NULL,"Muneeb",17);
 
-- TO ADD NEW COLUMNS USING ALTER
ALTER TABLE STUDENTS ADD DOB DATE, ADD GENDER VARCHAR(250), ADD COURSE VARCHAR(250), ADD FACULTY VARCHAR(250);

-- TO DROP COLUMNS USING ALTER
ALTER TABLE STUDENTS DROP DOB, DROP GENDER, DROP COURSE, DROP FACULTY;

-- TO APPLY PRIMARY KEY USING ALTER
ALTER TABLE STUDENTS MODIFY COLUMN ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL;
   

