-- TO CREATE DATABASE
CREATE DATABASE APT;

-- TO USE DATABASE
USE APT;

-- TO CREATE TABLE
CREATE TABLE ECH (
ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
NAME VARCHAR(250),
CLASS VARCHAR(250),
AGE INT,
SALARY VARCHAR(250)
);

-- TO SELECT TABLE
SELECT * FROM ECH; 

-- TO INSERT VALUES
INSERT INTO ECH values(NULL,"Khuzaima","SQL",24,"253000.00");
INSERT INTO ECH values(NULL,"Yousuf","SQL",20,"241000.00");
INSERT INTO ECH values(NULL,"Muneeb","SQL",17,"232000.00");
INSERT INTO ECH values(NULL,"Shoaib","SQL",21,"209030.00");
INSERT INTO ECH values(NULL,"Yahya","SQL",18,"199607.00");
INSERT INTO ECH values(NULL,"Ali Sher","SQL",20,"185046.00");
INSERT INTO ECH values(NULL,"Abdul Rehman","SQL",22,"177024.00");
INSERT INTO ECH values(NULL,"Faizan","SQL",25,"162099.00");
INSERT INTO ECH values(NULL,"Abdul Rafay","SQL",15,"151011.00");
INSERT INTO ECH values(NULL,"Huzaifa","SQL",20,"149023.00");

/* (1) AGGREGATE FUNCTIONS */
-- TO PERFORM SUM FUNCTION
SELECT SUM(SALARY) FROM ECH; 

-- TO PERFORM COUNT FUNCTION
SELECT COUNT(SALARY) FROM ECH;

-- TO PERFORM AVG FUNCTION
SELECT AVG(SALARY) FROM ECH;

-- TO PERFORM MAX FUNCTION
SELECT MAX(SALARY) FROM ECH;

-- TO PERFORM MIN FUNCTION
SELECT MIN(SALARY) FROM ECH; 

-- TO PERFORM FUNCTION WITH ALIAS (AS)
SELECT SUM(SALARY) AS "EMPLOYES SALARY" FROM ECH;

-- TO PERFORM FUNCTION WITH ALL COLUMNS    
SELECT *, MIN(SALARY) FROM ECH;

-- TO PERFORM FUNCTION WITH SPECIFIC COLUMNS
SELECT NAME,SALARY, MAX(SALARY) FROM ECH; 



/* (2) SCALAR FUNCTIONS */
-- TO PERFORM LOWER FUNCTION 
SELECT LOWER(NAME) FROM ECH;

-- TO PERFORM UPPER FUNCTION
SELECT UPPER(NAME) FROM ECH;

-- TO PERFORM SUBSTRING FUNCTION
SELECT NAME, SUBSTRING(NAME,2,5) FROM ECH;
  
-- TO PERFORM LENGTH FUNCTION
SELECT NAME, LENGTH(NAME) FROM ECH;

-- TO PERFORM ROUND FUNCTION
SELECT NAME, ROUND(SALARY) FROM ECH; 

-- TO PERFORM CURRENT TIMESTAMP FUNCTION
SELECT CURRENT_TIMESTAMP; 

-- TO PERFORM FORMAT FUNCTION
SELECT *, FORMAT(SALARY,4) FROM ECH; 

-- TO PERFORM FUNCTION WITH ALIAS
SELECT ID, ROUND(SALARY) AS "RoundValue" FROM ECH;

-- TO PERFORM FUNCTION WITH ALL COLUMNS
SELECT *, ROUND(SALARY) FROM ECH;

-- TO PERFORM FUNCTION WITH SPECIFIC COLUMNS
SELECT ID,NAME, ROUND(SALARY) FROM ECH;  