-- TO CREATE DATABASE
CREATE DATABASE APT;

-- TO USE DATABASE
USE APT;

-- TO CREATE TABLE
CREATE TABLE FAMILY (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    Name VARCHAR(250),
    Father_Name INT,
    FOREIGN KEY (Father_Name)
        REFERENCES FAMILY (ID)
);

-- TO DISPLAY THE TABLE
SELECT 
    *
FROM
    FAMILY;

-- TO INSERT VALUES INTO TABLE
INSERT INTO FAMILY (NAME) VALUES ("Mulla Abdul Rajab");
INSERT INTO FAMILY (NAME, Father_Name) VALUES ("Moulana Yaseen", 1);
INSERT INTO FAMILY (NAME, Father_Name) VALUES ("Abdul Majeed", 2);
INSERT INTO FAMILY (NAME, Father_Name) VALUES ("Abdul Raheem", 3);
INSERT INTO FAMILY (NAME, Father_Name) VALUES ("Jawed Iqbal", 4);
INSERT INTO FAMILY (NAME, Father_Name) VALUES ("Naveed Iqbal", 4);
INSERT INTO FAMILY (NAME, Father_Name) VALUES ("Parwez Iqbal", 4);
INSERT INTO FAMILY (NAME, Father_Name) VALUES ("Nadeem Iqbal", 4);
INSERT INTO FAMILY (NAME, Father_Name) VALUES ("Yousuf Naveed", 6);

-- TO PERFORM A SELF JOIN TO RETRIEVE FAMILY MEMBERS AND THEIR FATHERS' NAMES
-- QUERY 1: USING INNER JOIN
SELECT 
    A.Name AS 'NAME', B.Name AS 'FATHER NAME'
FROM
    FAMILY A
        INNER JOIN
    FAMILY B ON A.Father_Name = B.ID;

-- QUERY 2: USING WHERE CLAUSE
SELECT 
    A.Name AS 'NAME', B.Name AS 'FATHER NAME'
FROM
    FAMILY A,
    FAMILY B
WHERE
    A.Father_Name = B.ID;